site_name: Linux 101

theme:
    name: 'material'
    language: 'zh'

markdown_extensions:
    - admonition
    - footnotes
    - pymdownx.superfences
    - pymdownx.details

extra_css:
    - 'css/extra.css'

nav:
    - 负一：编写建议: advice.md
    - 零：前言: index.md
    - 一：初识 Linux: 
        - 讲义: Ch01/1.md
        - 补充内容: Ch01/1-supplement.md
    - 二：个性化配置与建站体验:
        - 讲义: Ch02/1.md
        - 补充内容: Ch02/1-supplement.md
    - 三：软件安装与文件操作:
        - 讲义: Ch03/1.md
        - 补充内容: Ch03/1-supplement.md
    - 四：进程、前后台、服务与例行性任务:
        - 讲义: Ch04/1.md
        - 补充内容: Ch04/1-supplement.md
    - 五：用户与用户组、文件权限、文件系统层次结构标准:
        - 讲义: Ch05/1.md
        - 补充内容: Ch05/1-supplement.md
    - 六：网络下载工具与 Shell 脚本:
        - 讲义: Ch06/1.md
        - 补充内容: Ch06/1-supplement.md
    - 七：Linux 上的编程:
        - 讲义: Ch07/1.md
        - 补充内容: Ch07/1-supplement.md
    - 八：Docker:
        - 讲义: Ch08/1.md
        - 补充内容: Ch08/1-supplement.md
    - 九：Shell 文字处理工具与正则表达式:
        - 讲义: Ch09/1.md
        - 补充内容: Ch09/1-supplement.md
    - 附录:
        - 内容一: Appendix/1.md

